### ISSUE TITLE
Mechanism to access buffer after an expectation

### ISSUE THREAD

**Issue by bbqsrc** [philippkeller/rexpect#2] opened 2017-09-14 10:14 UTC
A common pattern I've done in pexpect is something like the following:

```python
proc = pexpect.spawnu("foo")
proc.setecho(False)
proc.sendline("some input")
proc.expect("> ")
print(proc.before)
```

The `proc.before` part allows me to access the result of the input. Is there currently an equivalent in rexpect?

**Comment by philippkeller** [comment] 2017-09-15 05:17
For some reason I did not yet need to read back the output because I used rexpect more in a "integration test" manner than for automation.

That said, I just updated the code that `exp_*` are now returning the yet unread bytes including the matched string, so this is now possible:

```
let mut p = spawn("cat", Some(1000)).expect("cannot run cat");
p.send_line("lorem ipsum dolor sit amet")?;
assert_eq!("lorem ipsum dolor sit amet", p.exp_string("amet")?);
```

And in a more complete example (from your code it seems like you want to interact with bash, so probably you want to use `span_bash`. And the `setecho(False)` is set by spawn itself because I assumed that's the expected behaviour):

```
fn main() {
    || -> Result<()> {
        let mut p = spawn_bash(None)?;
        p.send_line("echo 'lorem ipsum'")?;
        let res = p.exp_char('>')?;
        println!("{}", res);

        Ok(())
    }().expect("example failed");
}
```

This example now prints 

```
lorem ipsum
[REXPECT_PROMPT>
```

Which does include the prompt being set by `spawn_bash`.

If this code change would suit your need I'd repackage it into a new version for cargo.

**Comment by philippkeller** [comment] 2017-09-16 13:04
after a few thoughts more: I would prefer actually to have `exp_*` return a tuple of:
1. the string *before* the match
2. the match itself (which is especially interesting in case of regex matches or `exp_any`).

@bbqsrc: any thoughts on this? Personally I didn't use pexpect too much so I don't have much real world examples in my experience. So if you can help here with some design decisions I would be glad

**Comment by bbqsrc** [comment] 2017-09-16 14:09
Both are fine, imho. My use case was using a morphological dictionary lookup tool. `pexpect` ended up being ridiculously slow, but when coming here to replicate it in Rust to see if the issue was just Python's GIL, I found there was no mechanism to get the response from the app being "expected".

Given your approach, the tuple approach is ideal, because if I am looking for a "> " prompt, I don't want to have to crop it out from the output I expect. This approach you propose would therefore make my life easier.

**Comment by philippkeller** [comment] 2017-09-18 04:49
I have updated the behaviour so rexpect internally both strings (before match, and match itself) are known.  `exp_string` now only returns string before match, and `exp_regex` for instance returns both before and match itself.

Your use case is probably best covered with this (which now only prints "lorem ipsum"):

```
fn main() {
    || -> Result<()> {
        let mut p = spawn_bash(None)?;
        p.send_line("echo 'lorem ipsum'")?;
        let res = p.wait_for_prompt()?;
        println!("{}", res);

        Ok(())
    }().expect("example failed");
}
```

I need to fix a bug still (`spawn_bash` seems to not delete the tmpfile upon exit) and then I'll push it to crates.io, if you want to test the speed you can use the dependency over a git dependency for now.

btw: I'd be very much interested to know the speed differences to pexpect. I think for normal use cases (especially when needing network) the speed difference is not much, in threaded cases it might be a difference though..

**Comment by philippkeller** [comment] 2017-09-27 14:48
I'm closing this as I just pushed the updated behaviour to crates.io
If this doesn't suit your need please reopen, @bbqsrc

**Closed by philippkeller** 2017-09-27 14:48 UTC
